import { describe, expect, it } from "vitest";
import {
  codeChip,
  codeTag,
  dumpAuditMarker,
  dumpCompletionMarker,
  dumpMarker,
} from "../index";
import { inferRefinementStatus } from "./refinement-status";
import {
  completedDumpIds,
  incompleteDumpIds,
} from "./dump-marker";

describe("dump marker grammar", () => {
  it("should infer refinada from a completion chip generated by the canonical grammar", () => {
    const status = inferRefinementStatus({
      description: "Como PO, quero exportar o relatório em CSV.",
      comments: [codeChip(dumpCompletionMarker("dump-4211"))],
    });

    expect(status).toBe("refinada");
  });

  it("should identify completed dump ids from markers generated by the canonical grammar", () => {
    const dumpIds = completedDumpIds([
      codeChip(dumpMarker("dump-parcial", "spec")),
      codeTag(dumpCompletionMarker("dump-concluido")),
    ]);

    expect(dumpIds).toEqual(["dump-concluido"]);
  });

  it("should identify incomplete dump ids from markers generated by the canonical grammar", () => {
    const dumpIds = incompleteDumpIds([
      codeTag(dumpMarker("dump-parcial", "spec")),
      codeChip(dumpMarker("dump-parcial", "decision:1")),
      codeChip(dumpCompletionMarker("dump-concluido")),
    ]);

    expect(dumpIds).toEqual(["dump-parcial"]);
  });

  it("should encode the gate's open questions in the durable dump audit", () => {
    expect(dumpAuditMarker("dump-4211", 2)).toBe(
      "sprint-griller:dump:dump-4211:audit:pending:2",
    );
  });

  it("should still read the legacy HTML comment markers that survived sanitization", () => {
    // Gravações da primeira geração usavam comentário HTML. Onde a instância
    // não os remove, continuam sendo artefatos válidos do dump.
    const dumpIds = completedDumpIds([
      `<!-- sprint-griller:dump:dump-legado:complete -->`,
    ]);

    expect(dumpIds).toEqual(["dump-legado"]);
  });

  it("should ignore markers quoted in prose without the code wrapper", () => {
    // Um humano citando o token cru na discussão não pode forjar a prova de
    // conclusão — só o chip, o <code> ou o legado comentário HTML contam.
    const dumpIds = completedDumpIds([
      "sprint-griller:dump:dump-citado:complete",
      "conversei sobre `sprint-griller:dump:dump-citado` no chat",
    ]);

    expect(dumpIds).toEqual([]);
  });
});
