import { describe, expect, it } from "vitest";
import { dumpAuditMarker, dumpCompletionMarker, dumpMarker } from "../index";
import { inferRefinementStatus } from "./refinement-status";
import {
  completedDumpIds,
  incompleteDumpIds,
} from "./dump-marker";

describe("dump marker grammar", () => {
  it("should infer refinada from a completion marker generated by the canonical grammar", () => {
    const status = inferRefinementStatus({
      description: "Como PO, quero exportar o relatório em CSV.",
      comments: [dumpCompletionMarker("dump-4211")],
    });

    expect(status).toBe("refinada");
  });

  it("should identify completed dump ids from markers generated by the canonical grammar", () => {
    const dumpIds = completedDumpIds([
      dumpMarker("dump-parcial", "spec"),
      dumpCompletionMarker("dump-concluido"),
    ]);

    expect(dumpIds).toEqual(["dump-concluido"]);
  });

  it("should identify incomplete dump ids from markers generated by the canonical grammar", () => {
    const dumpIds = incompleteDumpIds([
      dumpMarker("dump-parcial", "spec"),
      dumpMarker("dump-parcial", "decision:1"),
      dumpCompletionMarker("dump-concluido"),
    ]);

    expect(dumpIds).toEqual(["dump-parcial"]);
  });

  it("should encode the gate's open questions in the durable dump audit", () => {
    expect(dumpAuditMarker("dump-4211", 2)).toBe(
      "<!-- sprint-griller:dump:dump-4211:audit:pending:2 -->",
    );
  });
});
